name: bookihub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  camera: ^0.10.5+5
  dartz: ^0.10.1
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_native_splash: ^2.3.4
  flutter_phone_direct_caller: ^2.1.1
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6
  get_it: ^7.6.4
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  location: ^5.0.3
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  geocoding: ^2.1.1
  record_mp3: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.2.2
  google_maps_flutter: ^2.5.0
  

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: font\Inter-VariableFont_slnt,wght.ttf
